version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/app
    depends_on:
      - mongo
    environment:
      - DB_NAME=admin
      - DB_URI=@mongo:27017
      - DB_USERNAME=root
      - DB_PASSWORD=root
    # command: "node dist/app.js"
    command: "npm run start:dev" ## for development
    networks:
      - mongo-network

  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGODB_AUTH_DATABASE: admin
    volumes:
      - mongodb:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/ 
      MONGODB_AUTH_DATABASE: admin
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - mongo-network

volumes:
 mongodb:

networks: 
    mongo-network:
      driver: bridge